# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbf2c328c292696e59fefe0430b0d437ea004553e5e783ef7736b10aa342698b5c8f164de68f55c99c40ef9953cd0d6c8a49626740442c424e2817d286221008

test:
  secret_key_base: c30355fec8e79007152e6fe07972976a57f1e287723175f0079e25ea3e7bd223c3fc22382a2c85f1d7d8f3b7436d170ffb31a28bf69c345c589ae3c5684b2b85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
